=== clagomess/tomato/src/main/resources/io/github/clagomess/tomato/dto/data/request.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "createTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "updateTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "name": {
      "type": "string"
    },
    "method": {
      "type": "string",
      "enum": [
        "POST",
        "GET",
        "PUT",
        "DELETE",
        "HEAD",
        "OPTIONS",
        "PATCH"
      ]
    },
    "url": {
      "type": "string"
    },
    "urlParam": {
      "type": "object",
      "properties": {
        "charset": {
          "type": "string"
        },
        "path": {
          "$ref": "#/definitions/keyValueItem"
        },
        "query": {
          "$ref": "#/definitions/contentTypeKeyValueItem"
        }
      },
      "required": [
        "charset",
        "path",
        "query"
      ]
    },
    "headers": {
      "$ref": "#/definitions/keyValueItem"
    },
    "cookies": {
      "$ref": "#/definitions/keyValueItem"
    },
    "body": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "NO_BODY"
              ]
            },
            "charset": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "charset"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "RAW"
              ]
            },
            "charset": {
              "type": "string"
            },
            "raw": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "TEXT",
                    "JSON",
                    "XML",
                    "HTML"
                  ]
                },
                "raw": {
                  "type": "string"
                }
              },
              "required": [
                "type",
                "raw"
              ]
            }
          },
          "required": [
            "type",
            "charset",
            "raw"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "BINARY"
              ]
            },
            "binary": {
              "type": "object",
              "properties": {
                "contentType": {
                  "type": "string"
                },
                "file": {
                  "type": "string"
                }
              },
              "required": [
                "contentType",
                "file"
              ]
            }
          },
          "required": [
            "type",
            "binary"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "URL_ENCODED_FORM"
              ]
            },
            "charset": {
              "type": "string"
            },
            "urlEncodedForm": {
              "$ref": "#/definitions/contentTypeKeyValueItem"
            }
          },
          "required": [
            "type",
            "charset",
            "urlEncodedForm"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "MULTIPART_FORM"
              ]
            },
            "charset": {
              "type": "string"
            },
            "multiPartForm": {
              "$ref": "#/definitions/fileKeyValueItem"
            }
          },
          "required": [
            "type",
            "charset",
            "multiPartForm"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "createTime",
    "updateTime",
    "name",
    "method",
    "url",
    "body"
  ],
  "definitions": {
    "contentTypeKeyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "valueContentType": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "key",
          "value",
          "valueContentType",
          "selected"
        ]
      }
    },
    "fileKeyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TEXT",
              "FILE"
            ]
          },
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "valueContentType": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "type",
          "key",
          "value",
          "valueContentType",
          "selected"
        ]
      }
    },
    "keyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "key",
          "value",
          "selected"
        ]
      }
    }
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-i4L8x1ne/request-Dm078clh.json
{
  "id" : "Dm078clh",
  "createTime" : "2024-12-18T23:23:55",
  "updateTime" : "2025-03-08T00:08:30",
  "name" : "Response gzip",
  "method" : "GET",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ {
    "key" : "accept-encoding",
    "value" : "gzip",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-rppSDkLD.json
{
  "id" : "rppSDkLD",
  "createTime" : "2024-12-18T23:00:22",
  "updateTime" : "2025-02-06T13:39:38",
  "name" : "/echo.php",
  "method" : "POST",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/collection-KEbtdVhR/request-rppSDkLD.json
{
  "id" : "rppSDkLD",
  "createTime" : "2024-12-18T23:00:22",
  "updateTime" : "2025-03-08T00:06:26",
  "name" : "Basic POST",
  "method" : "POST",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/collection-KEbtdVhR/request-LrkL7hPM.json
{
  "id" : "LrkL7hPM",
  "createTime" : "2024-12-18T23:37:37",
  "updateTime" : "2025-03-08T00:06:16",
  "name" : "Basic DELETE",
  "method" : "DELETE",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-i4L8x1ne/request-55w7W0xw.json
{
  "id" : "55w7W0xw",
  "createTime" : "2024-12-18T23:06:02",
  "updateTime" : "2025-03-08T00:07:40",
  "name" : "Response Redirect",
  "method" : "GET",
  "url" : "{{echoServer}}/redirect.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-nPUaq0TC/collection-us62qhbS/collection-s8tPaxvJ/request-0b3cAtrM.json
{
  "id" : "0b3cAtrM",
  "createTime" : "2024-12-18T23:06:02",
  "updateTime" : "2025-02-06T13:43:45",
  "name" : "/sample-lvl2",
  "method" : "GET",
  "url" : "http://localhost:8080/sample-lvl2",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-IWBXn64Q.json
{
  "id" : "IWBXn64Q",
  "createTime" : "2024-12-18T23:39:42",
  "updateTime" : "2025-02-06T13:39:34",
  "name" : "/echo.php",
  "method" : "OPTIONS",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-UsxByseb.json
{
  "id" : "UsxByseb",
  "createTime" : "2024-12-18T23:02:11",
  "updateTime" : "2025-03-08T00:23:57",
  "name" : "Raw QueryParam",
  "method" : "GET",
  "url" : "http://localhost:8000/echo.php?param=value",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}
