=== clagomess/tomato/src/main/resources/io/github/clagomess/tomato/dto/data/request.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "createTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "updateTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "name": {
      "type": "string"
    },
    "method": {
      "type": "string",
      "enum": [
        "POST",
        "GET",
        "PUT",
        "DELETE",
        "HEAD",
        "OPTIONS",
        "PATCH"
      ]
    },
    "url": {
      "type": "string"
    },
    "urlParam": {
      "type": "object",
      "properties": {
        "charset": {
          "type": "string"
        },
        "path": {
          "$ref": "#/definitions/keyValueItem"
        },
        "query": {
          "$ref": "#/definitions/contentTypeKeyValueItem"
        }
      },
      "required": [
        "charset",
        "path",
        "query"
      ]
    },
    "headers": {
      "$ref": "#/definitions/keyValueItem"
    },
    "cookies": {
      "$ref": "#/definitions/keyValueItem"
    },
    "body": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "NO_BODY"
              ]
            },
            "charset": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "charset"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "RAW"
              ]
            },
            "charset": {
              "type": "string"
            },
            "raw": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "TEXT",
                    "JSON",
                    "XML",
                    "HTML"
                  ]
                },
                "raw": {
                  "type": "string"
                }
              },
              "required": [
                "type",
                "raw"
              ]
            }
          },
          "required": [
            "type",
            "charset",
            "raw"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "BINARY"
              ]
            },
            "binary": {
              "type": "object",
              "properties": {
                "contentType": {
                  "type": "string"
                },
                "file": {
                  "type": "string"
                }
              },
              "required": [
                "contentType",
                "file"
              ]
            }
          },
          "required": [
            "type",
            "binary"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "URL_ENCODED_FORM"
              ]
            },
            "charset": {
              "type": "string"
            },
            "urlEncodedForm": {
              "$ref": "#/definitions/contentTypeKeyValueItem"
            }
          },
          "required": [
            "type",
            "charset",
            "urlEncodedForm"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "MULTIPART_FORM"
              ]
            },
            "charset": {
              "type": "string"
            },
            "multiPartForm": {
              "$ref": "#/definitions/fileKeyValueItem"
            }
          },
          "required": [
            "type",
            "charset",
            "multiPartForm"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "createTime",
    "updateTime",
    "name",
    "method",
    "url",
    "body"
  ],
  "definitions": {
    "contentTypeKeyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "valueContentType": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "key",
          "value",
          "valueContentType",
          "selected"
        ]
      }
    },
    "fileKeyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TEXT",
              "FILE"
            ]
          },
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "valueContentType": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "type",
          "key",
          "value",
          "valueContentType",
          "selected"
        ]
      }
    },
    "keyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "key",
          "value",
          "selected"
        ]
      }
    }
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-7M2S0Kxh.json
{
  "id" : "7M2S0Kxh",
  "createTime" : "2024-12-18T23:28:53",
  "updateTime" : "2025-03-08T00:24:39",
  "name" : "URL Encoded Form",
  "method" : "POST",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "URL_ENCODED_FORM",
    "charset" : "UTF-8",
    "urlEncodedForm" : [ {
      "key" : "myparam1",
      "value" : "a",
      "selected" : true,
      "valueContentType" : "text/plain"
    }, {
      "key" : "myparam2",
      "value" : "b",
      "selected" : true,
      "valueContentType" : "text/plain"
    }, {
      "key" : "myparam3",
      "value" : "{{token}}",
      "selected" : true,
      "valueContentType" : "text/plain"
    }, {
      "key" : "disabledparam",
      "value" : "notSend!",
      "selected" : false,
      "valueContentType" : "text/plain"
    }, {
      "key" : "disabledparam2",
      "value" : "{{token}}",
      "selected" : false,
      "valueContentType" : "text/plain"
    } ]
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-tmCsbrzA.json
{
  "id" : "tmCsbrzA",
  "createTime" : "2024-12-18T23:26:19",
  "updateTime" : "2026-03-26T14:42:02",
  "name" : "Multipart Form",
  "method" : "POST",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "MULTIPART_FORM",
    "charset" : "UTF-8",
    "multiPartForm" : [ {
      "key" : "myparam",
      "value" : "123",
      "selected" : true,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    }, {
      "key" : "myfile",
      "value" : "/Users/claudio/OneDrive/Imagens/Portada.jpg",
      "selected" : true,
      "valueContentType" : "image/jpeg",
      "type" : "FILE"
    }, {
      "key" : "token",
      "value" : "{{token}}",
      "selected" : true,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    }, {
      "key" : "disabled1",
      "value" : "notSend!",
      "selected" : false,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    }, {
      "key" : "disabled2",
      "value" : "/Users/claudio/OneDrive/Imagens/WAF.png",
      "selected" : false,
      "valueContentType" : "image/png",
      "type" : "FILE"
    }, {
      "key" : "disabled3",
      "value" : "{{token}}",
      "selected" : false,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    } ]
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-60ODtoRs.json
{
  "id" : "60ODtoRs",
  "createTime" : "2024-12-18T22:57:29",
  "updateTime" : "2025-02-06T13:39:25",
  "name" : "/echo.php",
  "method" : "GET",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-SCUJoweU/request-rUqpR5UJ.json
{
  "id" : "rUqpR5UJ",
  "createTime" : "2025-01-20T14:00:36",
  "updateTime" : "2025-02-06T13:39:19",
  "name" : "/cookie.php",
  "method" : "GET",
  "url" : "{{echoServer}}/cookie.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-IEH5qenf/request-8EJRkvf4.json
{
  "id" : "8EJRkvf4",
  "createTime" : "2025-01-31T17:15:07",
  "updateTime" : "2025-03-08T00:14:24",
  "name" : "Body XML",
  "method" : "POST",
  "url" : "{{echoServer}}/echo-iso-8859-1.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "RAW",
    "charset" : "ISO-8859-1",
    "raw" : {
      "type" : "XML",
      "raw" : "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n<root>\n    <foo>Ação Açucar</foo>\n</root>"
    }
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-i4L8x1ne/request-4Ggthbte.json
{
  "id" : "4Ggthbte",
  "createTime" : "2024-12-18T23:20:09",
  "updateTime" : "2025-03-08T00:07:52",
  "name" : "Response PDF",
  "method" : "GET",
  "url" : "{{echoServer}}/sample.pdf",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-sZNFfOCY.json
{
  "id" : "sZNFfOCY",
  "createTime" : "2025-01-17T17:02:00",
  "updateTime" : "2025-03-08T00:24:06",
  "name" : "Variables Builder",
  "method" : "GET",
  "url" : "{{echoServer}}/echo.php?localtoken=:localtoken&disabled=:disabled",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ {
      "key" : "php",
      "value" : "echo.php",
      "selected" : true
    }, {
      "key" : "localtoken",
      "value" : "{{token}}",
      "selected" : true
    }, {
      "key" : "disabled",
      "value" : "no Inject",
      "selected" : false
    } ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-8bV40muQ.json
{
  "id" : "8bV40muQ",
  "createTime" : "2024-12-18T23:36:03",
  "updateTime" : "2025-03-08T00:24:47",
  "name" : "Json Body",
  "method" : "PUT",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "RAW",
    "charset" : "UTF-8",
    "raw" : {
      "type" : "JSON",
      "raw" : "{\n\t\"foo\": \"bar\"\n}"
    }
  }
}
