=== clagomess/tomato/src/main/resources/io/github/clagomess/tomato/dto/data/request.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "createTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "updateTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "name": {
      "type": "string"
    },
    "method": {
      "type": "string",
      "enum": [
        "POST",
        "GET",
        "PUT",
        "DELETE",
        "HEAD",
        "OPTIONS",
        "PATCH"
      ]
    },
    "url": {
      "type": "string"
    },
    "urlParam": {
      "type": "object",
      "properties": {
        "charset": {
          "type": "string"
        },
        "path": {
          "$ref": "#/definitions/keyValueItem"
        },
        "query": {
          "$ref": "#/definitions/contentTypeKeyValueItem"
        }
      },
      "required": [
        "charset",
        "path",
        "query"
      ]
    },
    "headers": {
      "$ref": "#/definitions/keyValueItem"
    },
    "cookies": {
      "$ref": "#/definitions/keyValueItem"
    },
    "body": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "NO_BODY"
              ]
            },
            "charset": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "charset"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "RAW"
              ]
            },
            "charset": {
              "type": "string"
            },
            "raw": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "TEXT",
                    "JSON",
                    "XML",
                    "HTML"
                  ]
                },
                "raw": {
                  "type": "string"
                }
              },
              "required": [
                "type",
                "raw"
              ]
            }
          },
          "required": [
            "type",
            "charset",
            "raw"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "BINARY"
              ]
            },
            "binary": {
              "type": "object",
              "properties": {
                "contentType": {
                  "type": "string"
                },
                "file": {
                  "type": "string"
                }
              },
              "required": [
                "contentType",
                "file"
              ]
            }
          },
          "required": [
            "type",
            "binary"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "URL_ENCODED_FORM"
              ]
            },
            "charset": {
              "type": "string"
            },
            "urlEncodedForm": {
              "$ref": "#/definitions/contentTypeKeyValueItem"
            }
          },
          "required": [
            "type",
            "charset",
            "urlEncodedForm"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "MULTIPART_FORM"
              ]
            },
            "charset": {
              "type": "string"
            },
            "multiPartForm": {
              "$ref": "#/definitions/fileKeyValueItem"
            }
          },
          "required": [
            "type",
            "charset",
            "multiPartForm"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "createTime",
    "updateTime",
    "name",
    "method",
    "url",
    "body"
  ],
  "definitions": {
    "contentTypeKeyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "valueContentType": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "key",
          "value",
          "valueContentType",
          "selected"
        ]
      }
    },
    "fileKeyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TEXT",
              "FILE"
            ]
          },
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "valueContentType": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "type",
          "key",
          "value",
          "valueContentType",
          "selected"
        ]
      }
    },
    "keyValueItem": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "key",
          "value",
          "selected"
        ]
      }
    }
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-eIrkVbCc.json
{
  "id" : "eIrkVbCc",
  "createTime" : "2025-01-17T16:59:24",
  "updateTime" : "2025-03-08T00:12:31",
  "name" : "Query Params Builder",
  "method" : "GET",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ {
      "key" : "myparam1",
      "value" : "teste",
      "selected" : true,
      "valueContentType" : "text/plain"
    }, {
      "key" : "myparam2",
      "value" : "<code> encoded",
      "selected" : true,
      "valueContentType" : "text/plain"
    }, {
      "key" : "myparam3",
      "value" : "{{token}}",
      "selected" : true,
      "valueContentType" : "text/plain"
    }, {
      "key" : "disabled",
      "value" : "no Send!",
      "selected" : false,
      "valueContentType" : "text/plain"
    } ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-IcWr9ZzV.json
{
  "id" : "IcWr9ZzV",
  "createTime" : "2024-12-18T23:38:23",
  "updateTime" : "2025-02-06T13:39:32",
  "name" : "/echo.php",
  "method" : "HEAD",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/collection-KEbtdVhR/request-bcjK27md.json
{
  "id" : "bcjK27md",
  "createTime" : "2024-12-18T23:40:07",
  "updateTime" : "2025-03-08T00:05:28",
  "name" : "Basic PATCH",
  "method" : "PATCH",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-SCUJoweU/request-Cio4Ribc.json
{
  "id" : "Cio4Ribc",
  "createTime" : "2024-12-18T23:17:18",
  "updateTime" : "2025-02-06T17:24:19",
  "name" : "send-cookie",
  "method" : "GET",
  "url" : "{{echoServer}}/cookie.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ {
    "key" : "PHPSESSID",
    "value" : "87cc08dd891bde98217c632cc073c897",
    "selected" : true
  } ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-tmCsbrzA.json
{
  "id" : "tmCsbrzA",
  "createTime" : "2024-12-18T23:26:19",
  "updateTime" : "2025-02-06T19:43:49",
  "name" : "multipart-form",
  "method" : "POST",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "MULTIPART_FORM",
    "charset" : "UTF-8",
    "multiPartForm" : [ {
      "key" : "myparam",
      "value" : "123",
      "selected" : true,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    }, {
      "key" : "myfile",
      "value" : "C:\\Users\\claudio\\OneDrive\\Documentos\\BhuiyanManuscript.pdf",
      "selected" : true,
      "valueContentType" : "application/pdf",
      "type" : "FILE"
    }, {
      "key" : "token",
      "value" : "{{token}}",
      "selected" : true,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    }, {
      "key" : "disabled1",
      "value" : "notSend!",
      "selected" : false,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    }, {
      "key" : "disabled2",
      "value" : "C:\\Users\\claudio\\OneDrive\\Documentos\\aaa.csv",
      "selected" : false,
      "valueContentType" : "text/plain",
      "type" : "FILE"
    }, {
      "key" : "disabled3",
      "value" : "{{token}}",
      "selected" : false,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    } ]
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-IEH5qenf/request-I1YypqBa.json
{
  "id" : "I1YypqBa",
  "createTime" : "2025-01-31T17:11:52",
  "updateTime" : "2025-02-06T13:40:27",
  "name" : "multipart-form",
  "method" : "POST",
  "url" : "{{echoServer}}/echo-iso-8859-1.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "MULTIPART_FORM",
    "charset" : "ISO-8859-1",
    "multiPartForm" : [ {
      "key" : "param1",
      "value" : "Ação Açucar",
      "selected" : true,
      "valueContentType" : "text/plain",
      "type" : "TEXT"
    } ]
  }
}

=== clagomess/tomato/src/test/resources/io/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-i4L8x1ne/request-keyXRqWc.json
{
  "id" : "keyXRqWc",
  "createTime" : "2024-12-18T23:15:15",
  "updateTime" : "2025-03-08T00:03:41",
  "name" : "Delay 6s",
  "method" : "GET",
  "url" : "{{echoServer}}/delay.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/collection-KEbtdVhR/request-IcWr9ZzV.json
{
  "id" : "IcWr9ZzV",
  "createTime" : "2024-12-18T23:38:23",
  "updateTime" : "2025-03-08T00:05:48",
  "name" : "Basic HEAD",
  "method" : "HEAD",
  "url" : "{{echoServer}}/echo.php",
  "urlParam" : {
    "charset" : "UTF-8",
    "path" : [ ],
    "query" : [ ]
  },
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY",
    "charset" : "UTF-8"
  }
}
