=== clagomess/tomato/src/main/resources/com/github/clagomess/tomato/dto/data/request.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "createTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "updateTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "name": {
      "type": "string"
    },
    "method": {
      "type": "string",
      "enum": [
        "POST",
        "GET",
        "PUT",
        "DELETE",
        "HEAD",
        "OPTIONS",
        "PATCH"
      ]
    },
    "url": {
      "type": "string"
    },
    "headers": {
      "$ref": "#/definitions/keyvalue"
    },
    "cookies": {
      "$ref": "#/definitions/keyvalue"
    },
    "body": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "NO_BODY"
              ]
            }
          },
          "required": [
            "type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "RAW"
              ]
            },
            "raw": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "TEXT",
                    "JSON",
                    "XML",
                    "HTML"
                  ]
                },
                "raw": {
                  "type": "string"
                }
              },
              "required": [
                "type",
                "raw"
              ]
            }
          },
          "required": [
            "type",
            "raw"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "BINARY"
              ]
            },
            "binary": {
              "type": "object",
              "properties": {
                "contentType": {
                  "type": "string"
                },
                "file": {
                  "type": "string"
                }
              },
              "required": [
                "contentType",
                "file"
              ]
            }
          },
          "required": [
            "type",
            "binary"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "URL_ENCODED_FORM"
              ]
            },
            "urlEncodedForm": {
              "$ref": "#/definitions/keyvalue"
            }
          },
          "required": [
            "type",
            "urlEncodedForm"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "MULTIPART_FORM"
              ]
            },
            "multiPartForm": {
              "$ref": "#/definitions/keyvalue"
            }
          },
          "required": [
            "type",
            "multiPartForm"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "createTime",
    "updateTime",
    "name",
    "method",
    "url",
    "body"
  ],
  "definitions": {
    "keyvalue": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TEXT",
              "FILE"
            ]
          },
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "type",
          "key",
          "value",
          "selected"
        ]
      }
    }
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-gtD5ZcKC.json
{
  "id" : "gtD5ZcKC",
  "createTime" : "2024-12-18T23:40:42",
  "updateTime" : "2024-12-18T23:44:02",
  "name" : "/hello-response-iso-8859-1",
  "method" : "GET",
  "url" : "http://localhost:8080/hello-response-iso-8859-1",
  "headers" : [ {
    "type" : "TEXT",
    "key" : "X-Set-Response-Content-Type",
    "value" : "text/xml; charset=iso-8859-1",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-tmCsbrzA.json
{
  "id" : "tmCsbrzA",
  "createTime" : "2024-12-18T23:26:19",
  "updateTime" : "2024-12-18T23:28:39",
  "name" : "/hello-multipart-form",
  "method" : "POST",
  "url" : "http://localhost:8080/hello-multipart-form",
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "MULTIPART_FORM",
    "multiPartForm" : [ {
      "type" : "TEXT",
      "key" : "myparam",
      "value" : "123",
      "selected" : true
    }, {
      "type" : "FILE",
      "key" : "myfile",
      "value" : "C:\\Users\\claudio\\OneDrive\\Documentos\\BhuiyanManuscript.pdf",
      "selected" : true
    } ]
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-lYK0zytu.json
{
  "id" : "lYK0zytu",
  "createTime" : "2024-12-18T23:13:33",
  "updateTime" : "2025-01-06T17:14:05",
  "name" : "/text-plain.txt",
  "method" : "GET",
  "url" : "http://localhost:8000/text-plain.txt",
  "headers" : [ {
    "type" : "TEXT",
    "key" : "X-Set-Response-Content-Type",
    "value" : "text/plain",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-Rm4aTjxJ.json
{
  "id" : "Rm4aTjxJ",
  "createTime" : "2024-12-18T23:30:14",
  "updateTime" : "2024-12-18T23:31:16",
  "name" : "/hello-body-json",
  "method" : "POST",
  "url" : "http://localhost:8080/hello-body-json",
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "RAW",
    "raw" : {
      "type" : "JSON",
      "raw" : "{\n\t\"hello\": \"world\"\n}\n"
    }
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-keyXRqWc.json
{
  "id" : "keyXRqWc",
  "createTime" : "2024-12-18T23:15:15",
  "updateTime" : "2024-12-18T23:16:22",
  "name" : "/hello-delay-6s",
  "method" : "GET",
  "url" : "http://localhost:8080/hello-delay-6s",
  "headers" : [ {
    "type" : "TEXT",
    "key" : "x-set-response-delay-ms",
    "value" : "6000",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-9LF0Losk.json
{
  "id" : "9LF0Losk",
  "createTime" : "2024-12-18T23:33:47",
  "updateTime" : "2025-01-06T16:56:40",
  "name" : "/echo.php?selected-file",
  "method" : "POST",
  "url" : "http://localhost:8000/echo.php?selected-file",
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "BINARY",
    "binary" : {
      "contentType" : "application/octet-stream",
      "file" : "C:\\Users\\claudio\\OneDrive\\Documentos\\BhuiyanManuscript.pdf"
    }
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-7M2S0Kxh.json
{
  "id" : "7M2S0Kxh",
  "createTime" : "2024-12-18T23:28:53",
  "updateTime" : "2025-01-06T16:54:59",
  "name" : "/echo.php?urlencoded-form",
  "method" : "POST",
  "url" : "http://localhost:8000/echo.php?urlencoded-form",
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "URL_ENCODED_FORM",
    "urlEncodedForm" : [ {
      "type" : "TEXT",
      "key" : "myparam1",
      "value" : "a",
      "selected" : true
    }, {
      "type" : "TEXT",
      "key" : "myparam2",
      "value" : "b",
      "selected" : true
    } ]
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-7M2S0Kxh.json
{
  "id" : "7M2S0Kxh",
  "createTime" : "2024-12-18T23:28:53",
  "updateTime" : "2025-01-08T16:29:34",
  "name" : "/echo.php?urlencoded-form",
  "method" : "POST",
  "url" : "{{echoServer}}/echo.php?urlencoded-form",
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "URL_ENCODED_FORM",
    "urlEncodedForm" : [ {
      "type" : "TEXT",
      "key" : "myparam1",
      "value" : "a",
      "selected" : true
    }, {
      "type" : "TEXT",
      "key" : "myparam2",
      "value" : "b",
      "selected" : true
    }, {
      "type" : "TEXT",
      "key" : "myparam3",
      "value" : "{{token}}",
      "selected" : true
    } ]
  }
}
