=== clagomess/tomato/src/main/resources/com/github/clagomess/tomato/dto/data/request.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "createTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "updateTime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$"
    },
    "name": {
      "type": "string"
    },
    "method": {
      "type": "string",
      "enum": [
        "POST",
        "GET",
        "PUT",
        "DELETE",
        "HEAD",
        "OPTIONS",
        "PATCH"
      ]
    },
    "url": {
      "type": "string"
    },
    "headers": {
      "$ref": "#/definitions/keyvalue"
    },
    "cookies": {
      "$ref": "#/definitions/keyvalue"
    },
    "body": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "NO_BODY"
              ]
            }
          },
          "required": [
            "type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "RAW"
              ]
            },
            "raw": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "TEXT",
                    "JSON",
                    "XML",
                    "HTML"
                  ]
                },
                "raw": {
                  "type": "string"
                }
              },
              "required": [
                "type",
                "raw"
              ]
            }
          },
          "required": [
            "type",
            "raw"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "BINARY"
              ]
            },
            "binary": {
              "type": "object",
              "properties": {
                "contentType": {
                  "type": "string"
                },
                "file": {
                  "type": "string"
                }
              },
              "required": [
                "contentType",
                "file"
              ]
            }
          },
          "required": [
            "type",
            "binary"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "URL_ENCODED_FORM"
              ]
            },
            "urlEncodedForm": {
              "$ref": "#/definitions/keyvalue"
            }
          },
          "required": [
            "type",
            "urlEncodedForm"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "MULTIPART_FORM"
              ]
            },
            "multiPartForm": {
              "$ref": "#/definitions/keyvalue"
            }
          },
          "required": [
            "type",
            "multiPartForm"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "createTime",
    "updateTime",
    "name",
    "method",
    "url",
    "body"
  ],
  "definitions": {
    "keyvalue": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TEXT",
              "FILE"
            ]
          },
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "selected": {
            "type": "boolean"
          }
        },
        "required": [
          "type",
          "key",
          "value",
          "selected"
        ]
      }
    }
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-4Ggthbte.json
{
  "id" : "4Ggthbte",
  "createTime" : "2024-12-18T23:20:09",
  "updateTime" : "2024-12-18T23:22:49",
  "name" : "/hello-content-pdf",
  "method" : "GET",
  "url" : "http://localhost:8080/hello-content-pdf",
  "headers" : [ {
    "type" : "TEXT",
    "key" : "x-set-response-content-type",
    "value" : "application/pdf",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-Cio4Ribc.json
{
  "id" : "Cio4Ribc",
  "createTime" : "2024-12-18T23:17:18",
  "updateTime" : "2024-12-18T23:18:40",
  "name" : "/hello-cookie",
  "method" : "GET",
  "url" : "http://localhost:8080/hello-cookie",
  "headers" : [ ],
  "cookies" : [ {
    "type" : "TEXT",
    "key" : "JSESSIONID",
    "value" : "50AE9F57B058D16C887177D9C79EF364",
    "selected" : true
  } ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-x4woN3gk.json
{
  "id" : "x4woN3gk",
  "createTime" : "2024-12-18T23:04:19",
  "updateTime" : "2024-12-18T23:05:35",
  "name" : "/hello-custom-header",
  "method" : "GET",
  "url" : "http://localhost:8080/hello-custom-header",
  "headers" : [ {
    "type" : "TEXT",
    "key" : "X-Burger",
    "value" : "ichi",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-55w7W0xw.json
{
  "id" : "55w7W0xw",
  "createTime" : "2024-12-18T23:06:02",
  "updateTime" : "2025-01-08T11:18:56",
  "name" : "/redirect.php",
  "method" : "GET",
  "url" : "{{echoServer}}/redirect.php",
  "headers" : [ {
    "type" : "TEXT",
    "key" : "x-set-response-status-code",
    "value" : "301",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/io/repository/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-gtD5ZcKC.json
{
  "id" : "gtD5ZcKC",
  "createTime" : "2024-12-18T23:40:42",
  "updateTime" : "2025-01-08T11:19:36",
  "name" : "/xml-iso-8859-1.php",
  "method" : "GET",
  "url" : "{{echoServer}}/xml-iso-8859-1.php",
  "headers" : [ {
    "type" : "TEXT",
    "key" : "X-Set-Response-Content-Type",
    "value" : "text/xml; charset=iso-8859-1",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-Dm078clh.json
{
  "id" : "Dm078clh",
  "createTime" : "2024-12-18T23:23:55",
  "updateTime" : "2024-12-18T23:25:21",
  "name" : "/hello-gzip",
  "method" : "GET",
  "url" : "http://localhost:8080/hello-gzip",
  "headers" : [ {
    "type" : "TEXT",
    "key" : "accept-encoding",
    "value" : "gzip",
    "selected" : true
  } ],
  "cookies" : [ ],
  "body" : {
    "type" : "NO_BODY"
  }
}

=== clagomess/tomato/src/test/resources/com/github/clagomess/tomato/service/DataServiceTest/home/data/workspace-JNtdCPvw/collection-a70uf9Xv/request-8bV40muQ.json
{
  "id" : "8bV40muQ",
  "createTime" : "2024-12-18T23:36:03",
  "updateTime" : "2024-12-18T23:37:34",
  "name" : "/hello",
  "method" : "PUT",
  "url" : "http://localhost:8080/hello",
  "headers" : [ ],
  "cookies" : [ ],
  "body" : {
    "type" : "RAW",
    "raw" : {
      "type" : "JSON",
      "raw" : "{\n\t\"foo\": \"bar\"\n}"
    }
  }
}
